// 错误码集中定义；service（api 层）与 controller（store 层）各自包装异常，
// 展示层通过 errorMessages 映射为中文提示。
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  IMPORT_EMPTY: "IMPORT_EMPTY",
  PARSE_NO_SECTION: "PARSE_NO_SECTION",
  SAME_DOCUMENT: "SAME_DOCUMENT",
  SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  NOTE_INVALID: "NOTE_INVALID",
  PAIR_NOT_FOUND: "PAIR_NOT_FOUND",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  EXPORT_FAILED: "EXPORT_FAILED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
