/** 错误码集中位置，service 与 controller(api) 分别包装，禁止单一位置吞掉全部异常 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PARSE_FAILED: "PARSE_FAILED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  DIFF_NOT_FOUND: "DIFF_NOT_FOUND",
  REVIEW_NOTE_NOT_FOUND: "REVIEW_NOTE_NOT_FOUND",
  DUPLICATE_VERSION: "DUPLICATE_VERSION",
  SAME_VERSION_COMPARE: "SAME_VERSION_COMPARE",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  EXPORT_FAILED: "EXPORT_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
